from typing import List, Optional, Protocol

from vaybooks.bms.domain.business.time_tracking.entities import BusinessTimeEntry


class BusinessTimeTrackingRepository(Protocol):
    def save(self, entry: BusinessTimeEntry) -> BusinessTimeEntry: ...

    def find_by_id(self, entry_id: str) -> Optional[BusinessTimeEntry]: ...

    def find_by_task(self, task_id: str) -> List[BusinessTimeEntry]: ...

    def list_all(self) -> List[BusinessTimeEntry]: ...

    def delete(self, entry_id: str) -> None: ...
