export {
  BoutiqueOverviewPage,
  BoutiqueOrdersListPage,
  BoutiqueOrderDetailPage,
  BoutiqueOrderWorkspacePage,
  BoutiqueItemsListPage,
  BoutiqueItemDetailPage,
  BoutiqueMeasurementsListPage,
  BoutiqueMeasurementDetailPage,
  BoutiqueTimePage,
  BoutiqueTimeLogPage,
  BoutiqueCalendarPage,
  BoutiqueTaskDetailPage,
  BoutiqueReportsPage,
  BoutiqueScheduledReportsPage,
} from './pages';
