from typing import List, Optional, Protocol

from vaybooks.bms.domain.entitlements.entities import FeatureFlag, OrgEntitlement, Plan


class FeatureFlagRepository(Protocol):
    def save(self, flag: FeatureFlag) -> FeatureFlag: ...

    def find_by_key(self, key: str) -> Optional[FeatureFlag]: ...

    def list_all(self) -> List[FeatureFlag]: ...


class PlanRepository(Protocol):
    def save(self, plan: Plan) -> Plan: ...

    def find_by_id(self, plan_id: str) -> Optional[Plan]: ...

    def list_all(self) -> List[Plan]: ...

    def delete(self, plan_id: str) -> None: ...


class OrgEntitlementRepository(Protocol):
    def get(self, org_id: str | None = None) -> Optional[OrgEntitlement]: ...

    def save(self, entitlement: OrgEntitlement) -> OrgEntitlement: ...
