from typing import List, Optional, Protocol

from vaybooks.bms.domain.identity.entities import Role, User


class UserRepository(Protocol):
    def save(self, user: User) -> User: ...

    def find_by_id(self, user_id: str) -> Optional[User]: ...

    def find_by_username(
        self, username: str, org_id: str | None = None
    ) -> Optional[User]: ...

    def list_all(self) -> List[User]: ...

    def delete(self, user_id: str) -> None: ...


class RoleRepository(Protocol):
    def save(self, role: Role) -> Role: ...

    def find_by_id(self, role_id: str) -> Optional[Role]: ...

    def find_by_name(self, name: str) -> Optional[Role]: ...

    def list_all(self) -> List[Role]: ...

    def delete(self, role_id: str) -> None: ...
