from __future__ import annotations

from typing import List, Optional, Protocol

from vaybooks.bms.domain.projects.activity_catalog import ProjectActivityConfig
from vaybooks.bms.domain.projects.boq import ProjectBoqItem
from vaybooks.bms.domain.projects.budget import (
    ProjectBudgetHeader,
    ProjectBudgetLine,
    ProjectBudgetRevision,
)
from vaybooks.bms.domain.projects.cash_flow import ProjectCashFlowPlan
from vaybooks.bms.domain.projects.dpr import ProjectDpr
from vaybooks.bms.domain.projects.enquiry import ProjectEnquiry, ProjectSiteAssessment
from vaybooks.bms.domain.projects.entities import (
    Project,
    ProjectCostTransfer,
    ProjectDocument,
    ProjectExpense,
    ProjectProforma,
    ProjectQuotation,
    ProjectRetentionEntry,
    ProjectTemplate,
    ProjectTimeEntry,
    ProjectVariation,
    ProjectWorkOrder,
    ProjectWriteOff,
)
from vaybooks.bms.domain.projects.measurement import ProjectMeasurement, ProjectRABill
from vaybooks.bms.domain.projects.petty_cash import ProjectPettyCashAdvance
from vaybooks.bms.domain.projects.procurement import (
    ProjectMaterialRequest,
    ProjectRfq,
    ProjectSiteStockMovement,
)
from vaybooks.bms.domain.projects.quality_config import (
    ProjectConfigSnapshot,
    ProjectHandover,
    ProjectQualityIssue,
    ProjectWbsNode,
)
from vaybooks.bms.domain.projects.recognition import (
    ProjectRecognitionEntry,
    ProjectReconciliation,
)
from vaybooks.bms.domain.projects.subcontract import ProjectSubcontractOrder
from vaybooks.bms.domain.shared.enums import (
    ProjectDocumentCategory,
    ProjectEnquiryStatus,
    ProjectStatus,
)


class ProjectTemplateRepository(Protocol):
    def save(self, template: ProjectTemplate) -> ProjectTemplate: ...

    def find_by_id(self, template_id: str) -> Optional[ProjectTemplate]: ...

    def list_all(self) -> List[ProjectTemplate]: ...

    def delete(self, template_id: str) -> None: ...


class ProjectRepository(Protocol):
    def save(self, project: Project) -> Project: ...

    def find_by_id(self, project_id: str) -> Optional[Project]: ...

    def list_all(self, status: Optional[ProjectStatus] = None) -> List[Project]: ...

    def search(self, query: str = "") -> List[Project]: ...

    def count_by_customer(self, customer_id: str) -> int: ...

    def list_by_customer(self, customer_id: str) -> List[Project]: ...

    def get_customer_summary(self, customer_id: str) -> dict: ...


class ProjectDocumentRepository(Protocol):
    def save(self, document: ProjectDocument) -> ProjectDocument: ...

    def find_by_id(self, document_id: str) -> Optional[ProjectDocument]: ...

    def list_by_project(
        self,
        project_id: str,
        include_deleted: bool = False,
        category: Optional[ProjectDocumentCategory] = None,
    ) -> List[ProjectDocument]: ...

    def soft_delete(self, document_id: str) -> None: ...


class ProjectTimeEntryRepository(Protocol):
    def save(self, entry: ProjectTimeEntry) -> ProjectTimeEntry: ...

    def save_many(self, entries: List[ProjectTimeEntry]) -> List[ProjectTimeEntry]: ...

    def find_by_id(self, entry_id: str) -> Optional[ProjectTimeEntry]: ...

    def list_by_project(self, project_id: str) -> List[ProjectTimeEntry]: ...

    def list_by_activity(self, activity_id: str) -> List[ProjectTimeEntry]: ...

    def list_by_worker(self, worker_id: str) -> List[ProjectTimeEntry]: ...

    def delete(self, entry_id: str) -> None: ...


class ProjectExpenseRepository(Protocol):
    def save(self, expense: ProjectExpense) -> ProjectExpense: ...

    def find_by_id(self, expense_id: str) -> Optional[ProjectExpense]: ...

    def list_by_project(self, project_id: str) -> List[ProjectExpense]: ...

    def delete(self, expense_id: str) -> None: ...


class ProjectQuotationRepository(Protocol):
    def save(self, quotation: ProjectQuotation) -> ProjectQuotation: ...

    def find_by_id(self, quotation_id: str) -> Optional[ProjectQuotation]: ...

    def list_by_project(self, project_id: str) -> List[ProjectQuotation]: ...

    def list_all(self) -> List[ProjectQuotation]: ...


class ProjectWorkOrderRepository(Protocol):
    def save(self, work_order: ProjectWorkOrder) -> ProjectWorkOrder: ...

    def find_by_id(self, wo_id: str) -> Optional[ProjectWorkOrder]: ...

    def list_by_project(self, project_id: str) -> List[ProjectWorkOrder]: ...


class ProjectRABillRepository(Protocol):
    def save(self, ra_bill: ProjectRABill) -> ProjectRABill: ...

    def find_by_id(self, ra_id: str) -> Optional[ProjectRABill]: ...

    def list_by_project(self, project_id: str) -> List[ProjectRABill]: ...


class ProjectProformaRepository(Protocol):
    def save(self, proforma: ProjectProforma) -> ProjectProforma: ...

    def find_by_id(self, proforma_id: str) -> Optional[ProjectProforma]: ...

    def list_by_project(self, project_id: str) -> List[ProjectProforma]: ...


class ProjectVariationRepository(Protocol):
    def save(self, variation: ProjectVariation) -> ProjectVariation: ...

    def find_by_id(self, variation_id: str) -> Optional[ProjectVariation]: ...

    def list_by_project(self, project_id: str) -> List[ProjectVariation]: ...


class ProjectRetentionRepository(Protocol):
    def save(self, entry: ProjectRetentionEntry) -> ProjectRetentionEntry: ...

    def find_by_id(self, entry_id: str) -> Optional[ProjectRetentionEntry]: ...

    def list_by_project(self, project_id: str) -> List[ProjectRetentionEntry]: ...


class ProjectCostTransferRepository(Protocol):
    def save(self, transfer: ProjectCostTransfer) -> ProjectCostTransfer: ...

    def find_by_id(self, transfer_id: str) -> Optional[ProjectCostTransfer]: ...

    def list_by_project(self, project_id: str) -> List[ProjectCostTransfer]: ...


class ProjectWriteOffRepository(Protocol):
    def save(self, write_off: ProjectWriteOff) -> ProjectWriteOff: ...

    def find_by_id(self, write_off_id: str) -> Optional[ProjectWriteOff]: ...

    def list_by_project(self, project_id: str) -> List[ProjectWriteOff]: ...


class ProjectBoqRepository(Protocol):
    def save(self, item: ProjectBoqItem) -> ProjectBoqItem: ...

    def save_many(self, items: List[ProjectBoqItem]) -> List[ProjectBoqItem]: ...

    def find_by_id(self, item_id: str) -> Optional[ProjectBoqItem]: ...

    def list_by_project(self, project_id: str) -> List[ProjectBoqItem]: ...

    def delete(self, item_id: str) -> None: ...


class ProjectBudgetRepository(Protocol):
    def save_line(self, line: ProjectBudgetLine) -> ProjectBudgetLine: ...

    def save_lines(self, lines: List[ProjectBudgetLine]) -> List[ProjectBudgetLine]: ...

    def find_line_by_id(self, line_id: str) -> Optional[ProjectBudgetLine]: ...

    def list_lines_by_project(self, project_id: str) -> List[ProjectBudgetLine]: ...

    def save_revision(self, revision: ProjectBudgetRevision) -> ProjectBudgetRevision: ...

    def list_revisions_by_project(self, project_id: str) -> List[ProjectBudgetRevision]: ...

    def save_header(self, header: ProjectBudgetHeader) -> ProjectBudgetHeader: ...

    def find_header_by_project(
        self, project_id: str
    ) -> Optional[ProjectBudgetHeader]: ...


class ProjectCashFlowRepository(Protocol):
    def save(self, plan: ProjectCashFlowPlan) -> ProjectCashFlowPlan: ...

    def find_by_id(self, plan_id: str) -> Optional[ProjectCashFlowPlan]: ...

    def list_by_project(self, project_id: str) -> List[ProjectCashFlowPlan]: ...


class ProjectMeasurementRepository(Protocol):
    def save(self, measurement: ProjectMeasurement) -> ProjectMeasurement: ...

    def find_by_id(self, measurement_id: str) -> Optional[ProjectMeasurement]: ...

    def list_by_project(self, project_id: str) -> List[ProjectMeasurement]: ...

    def list_by_boq_item(self, boq_item_id: str) -> List[ProjectMeasurement]: ...

    def delete(self, measurement_id: str) -> None: ...


class ProjectActivityConfigRepository(Protocol):
    def save(self, config: ProjectActivityConfig) -> ProjectActivityConfig: ...

    def find_by_id(self, config_id: str) -> Optional[ProjectActivityConfig]: ...

    def find_by_name(self, name: str) -> Optional[ProjectActivityConfig]: ...

    def list_all(self, active_only: bool = True) -> List[ProjectActivityConfig]: ...

    def delete(self, config_id: str) -> None: ...


class ProjectEnquiryRepository(Protocol):
    def save_enquiry(self, enquiry: ProjectEnquiry) -> ProjectEnquiry: ...

    def find_enquiry_by_id(self, enquiry_id: str) -> Optional[ProjectEnquiry]: ...

    def list_enquiries(
        self, status: Optional[ProjectEnquiryStatus] = None
    ) -> List[ProjectEnquiry]: ...

    def save_assessment(
        self, assessment: ProjectSiteAssessment
    ) -> ProjectSiteAssessment: ...

    def find_assessment_by_id(
        self, assessment_id: str
    ) -> Optional[ProjectSiteAssessment]: ...

    def list_assessments_by_enquiry(
        self, enquiry_id: str
    ) -> List[ProjectSiteAssessment]: ...


class ProjectDprRepository(Protocol):
    def save(self, dpr: ProjectDpr) -> ProjectDpr: ...

    def find_by_id(self, dpr_id: str) -> Optional[ProjectDpr]: ...

    def find_by_idempotency_key(self, key: str) -> Optional[ProjectDpr]: ...

    def list_by_project(self, project_id: str) -> List[ProjectDpr]: ...


class ProjectProcurementRepository(Protocol):
    def save_material_request(
        self, mr: ProjectMaterialRequest
    ) -> ProjectMaterialRequest: ...

    def find_material_request_by_id(
        self, mr_id: str
    ) -> Optional[ProjectMaterialRequest]: ...

    def list_material_requests_by_project(
        self, project_id: str
    ) -> List[ProjectMaterialRequest]: ...

    def save_rfq(self, rfq: ProjectRfq) -> ProjectRfq: ...

    def find_rfq_by_id(self, rfq_id: str) -> Optional[ProjectRfq]: ...

    def list_rfqs_by_project(self, project_id: str) -> List[ProjectRfq]: ...

    def save_stock_movement(
        self, movement: ProjectSiteStockMovement
    ) -> ProjectSiteStockMovement: ...

    def find_stock_movement_by_id(
        self, movement_id: str
    ) -> Optional[ProjectSiteStockMovement]: ...

    def list_stock_movements_by_project(
        self, project_id: str
    ) -> List[ProjectSiteStockMovement]: ...


class ProjectSubcontractRepository(Protocol):
    def save(self, order: ProjectSubcontractOrder) -> ProjectSubcontractOrder: ...

    def find_by_id(self, order_id: str) -> Optional[ProjectSubcontractOrder]: ...

    def list_by_project(self, project_id: str) -> List[ProjectSubcontractOrder]: ...


class ProjectPettyCashRepository(Protocol):
    def save(self, advance: ProjectPettyCashAdvance) -> ProjectPettyCashAdvance: ...

    def find_by_id(self, advance_id: str) -> Optional[ProjectPettyCashAdvance]: ...

    def list_by_project(self, project_id: str) -> List[ProjectPettyCashAdvance]: ...


class ProjectRecognitionRepository(Protocol):
    def save_entry(self, entry: ProjectRecognitionEntry) -> ProjectRecognitionEntry: ...

    def find_entry_by_id(self, entry_id: str) -> Optional[ProjectRecognitionEntry]: ...

    def find_entry_by_idempotency_key(
        self, key: str
    ) -> Optional[ProjectRecognitionEntry]: ...

    def list_entries_by_project(
        self, project_id: str
    ) -> List[ProjectRecognitionEntry]: ...

    def save_reconciliation(
        self, recon: ProjectReconciliation
    ) -> ProjectReconciliation: ...

    def find_reconciliation_by_id(
        self, recon_id: str
    ) -> Optional[ProjectReconciliation]: ...

    def list_reconciliations_by_project(
        self, project_id: str
    ) -> List[ProjectReconciliation]: ...


class ProjectQualityConfigRepository(Protocol):
    def save_quality_issue(self, issue: ProjectQualityIssue) -> ProjectQualityIssue: ...

    def find_quality_issue_by_id(
        self, issue_id: str
    ) -> Optional[ProjectQualityIssue]: ...

    def list_quality_issues_by_project(
        self, project_id: str
    ) -> List[ProjectQualityIssue]: ...

    def save_handover(self, handover: ProjectHandover) -> ProjectHandover: ...

    def find_handover_by_project(self, project_id: str) -> Optional[ProjectHandover]: ...

    def find_handover_by_id(self, handover_id: str) -> Optional[ProjectHandover]: ...

    def save_wbs_node(self, node: ProjectWbsNode) -> ProjectWbsNode: ...

    def find_wbs_node_by_id(self, node_id: str) -> Optional[ProjectWbsNode]: ...

    def list_wbs_nodes_by_project(self, project_id: str) -> List[ProjectWbsNode]: ...

    def save_config_snapshot(
        self, snapshot: ProjectConfigSnapshot
    ) -> ProjectConfigSnapshot: ...

    def find_config_snapshot_by_id(
        self, snapshot_id: str
    ) -> Optional[ProjectConfigSnapshot]: ...

    def list_config_snapshots_by_project(
        self, project_id: str
    ) -> List[ProjectConfigSnapshot]: ...
