import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  ArrowLeftRight,
  BadgeDollarSign,
  BarChart3,
  BookOpen,
  Boxes,
  Building2,
  CalendarClock,
  CalendarDays,
  ClipboardList,
  Clock,
  CreditCard,
  Database,
  FileSignature,
  FileText,
  Flag,
  FlaskConical,
  FolderKanban,
  Handshake,
  HardDrive,
  Keyboard,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  Layers,
  MapPin,
  MessageSquare,
  Notebook,
  Package,
  PackageCheck,
  Percent,
  Plus,
  Printer,
  Receipt,
  RefreshCw,
  Ruler,
  Scale,
  ScrollText,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Tags,
  Truck,
  Undo2,
  UserCog,
  UserPlus,
  Users,
  UsersRound,
  Wallet,
  Warehouse,
} from 'lucide-react';
import type { NavIcon } from '../navConfig';

const ICONS: Record<NavIcon, LucideIcon> = {
  dashboard: LayoutDashboard,
  calendarDays: CalendarDays,
  users: Users,
  truck: Truck,
  handshake: Handshake,
  userCog: UserCog,
  tags: Tags,
  layoutGrid: LayoutGrid,
  userPlus: UserPlus,
  messageSquare: MessageSquare,
  activity: Activity,
  barChart: BarChart3,
  clock: Clock,
  shoppingBag: ShoppingBag,
  ruler: Ruler,
  package: Package,
  folderKanban: FolderKanban,
  clipboardList: ClipboardList,
  fileText: FileText,
  fileSignature: FileSignature,
  receipt: Receipt,
  undo: Undo2,
  shoppingCart: ShoppingCart,
  packageCheck: PackageCheck,
  boxes: Boxes,
  warehouse: Warehouse,
  arrowLeftRight: ArrowLeftRight,
  badgeDollar: BadgeDollarSign,
  flaskConical: FlaskConical,
  layers: Layers,
  bookOpen: BookOpen,
  percent: Percent,
  scale: Scale,
  landmark: Landmark,
  wallet: Wallet,
  creditCard: CreditCard,
  notebook: Notebook,
  balanceScale: Scale,
  hardDrive: HardDrive,
  settings: Settings,
  refreshCw: RefreshCw,
  scrollText: ScrollText,
  building: Building2,
  mapPin: MapPin,
  printer: Printer,
  keyboard: Keyboard,
  sliders: SlidersHorizontal,
  flag: Flag,
  shield: Shield,
  keyRound: KeyRound,
  usersRound: UsersRound,
  database: Database,
  calendarClock: CalendarClock,
  plus: Plus,
};

export function NavGlyph({
  name,
  size = 18,
  className,
}: {
  name?: NavIcon;
  size?: number;
  className?: string;
}) {
  if (!name) return null;
  const Icon = ICONS[name];
  if (!Icon) return null;
  return <Icon size={size} strokeWidth={1.75} className={className} aria-hidden />;
}
