from typing import List, Optional, Protocol

from vaybooks.bms.domain.inventory.entities import (
    CatalogProduct,
    InventoryProduct,
    Location,
    ProductCategory,
    ProductUnit,
    StockBalance,
    StockMovement,
    StockTransfer,
    Warehouse,
)
from vaybooks.bms.domain.inventory.field_definitions import ProductFieldDefinition
from vaybooks.bms.domain.shared.enums import LocationType


class ProductUnitRepository(Protocol):
    def save(self, unit: ProductUnit) -> ProductUnit: ...

    def find_by_id(self, unit_id: str) -> Optional[ProductUnit]: ...

    def find_by_code(self, code: str) -> Optional[ProductUnit]: ...

    def list_all(self, active_only: bool = True) -> List[ProductUnit]: ...

    def search(
        self, query: str, *, active_only: bool = True, limit: int = 25
    ) -> List[ProductUnit]: ...

    def count_products_using(self, unit_id: str) -> int: ...


class ProductCategoryRepository(Protocol):
    def save(self, category: ProductCategory) -> ProductCategory: ...

    def find_by_id(self, category_id: str) -> Optional[ProductCategory]: ...

    def find_by_ids(self, category_ids: List[str]) -> List[ProductCategory]: ...

    def find_by_name(self, name: str) -> Optional[ProductCategory]: ...

    def find_by_parent_and_name(
        self, parent_id: Optional[str], name: str
    ) -> Optional[ProductCategory]: ...

    def list_all(self, active_only: bool = True) -> List[ProductCategory]: ...

    def search(
        self, query: str, *, active_only: bool = True, limit: int = 25
    ) -> List[ProductCategory]: ...

    def list_children(self, parent_id: Optional[str]) -> List[ProductCategory]: ...

    def delete(self, category_id: str) -> None: ...


class LocationRepository(Protocol):
    def save(self, location: Location) -> Location: ...

    def find_by_id(self, location_id: str) -> Optional[Location]: ...

    def find_by_code(self, code: str) -> Optional[Location]: ...

    def list_all(
        self,
        active_only: bool = True,
        location_type: Optional[LocationType] = None,
    ) -> List[Location]: ...

    def search(
        self,
        query: str,
        *,
        active_only: bool = True,
        limit: int = 25,
        location_type: Optional[LocationType] = None,
    ) -> List[Location]: ...

    def delete(self, location_id: str) -> None: ...


# Back-compat alias
WarehouseRepository = LocationRepository


class CatalogProductRepository(Protocol):
    def save(self, product: CatalogProduct) -> CatalogProduct: ...

    def find_by_id(self, product_id: str) -> Optional[CatalogProduct]: ...

    def list_all(self, active_only: bool = True) -> List[CatalogProduct]: ...

    def list_by_category(self, category_id: str) -> List[CatalogProduct]: ...

    def search(self, query: str) -> List[CatalogProduct]: ...


class InventoryProductRepository(Protocol):
    def save(self, product: InventoryProduct) -> InventoryProduct: ...

    def find_by_id(self, product_id: str) -> Optional[InventoryProduct]: ...

    def find_by_sku(self, sku: str) -> Optional[InventoryProduct]: ...

    def list_all(self, active_only: bool = True) -> List[InventoryProduct]: ...

    def list_by_category(self, category_id: str) -> List[InventoryProduct]: ...

    def list_by_catalog_product(self, catalog_product_id: str) -> List[InventoryProduct]: ...

    def count_by_category(self, category_id: str) -> int: ...

    def count_by_unit(self, unit_id: str) -> int: ...

    def search(self, query: str) -> List[InventoryProduct]: ...


class ProductFieldDefinitionRepository(Protocol):
    def save(self, definition: ProductFieldDefinition) -> ProductFieldDefinition: ...

    def find_by_id(self, definition_id: str) -> Optional[ProductFieldDefinition]: ...

    def find_by_key(self, key: str) -> Optional[ProductFieldDefinition]: ...

    def list_all(self, active_only: bool = False) -> List[ProductFieldDefinition]: ...

    def delete(self, definition_id: str) -> None: ...


class StockMovementRepository(Protocol):
    def save(self, movement: StockMovement) -> StockMovement: ...

    def list_by_product(self, product_id: str) -> List[StockMovement]: ...

    def list_all(self) -> List[StockMovement]: ...

    def list_by_reference(self, reference_id: str) -> List[StockMovement]: ...

    def list_by_location(self, location_id: str) -> List[StockMovement]: ...

    def delete(self, movement_id: str) -> None: ...


class StockBalanceRepository(Protocol):
    def save(self, balance: StockBalance) -> StockBalance: ...

    def get(self, product_id: str, location_id: str) -> Optional[StockBalance]: ...

    def list_by_product(self, product_id: str) -> List[StockBalance]: ...

    def list_by_location(self, location_id: str) -> List[StockBalance]: ...

    def list_all(self) -> List[StockBalance]: ...

    def delete(self, balance_id: str) -> None: ...


class StockTransferRepository(Protocol):
    def save(self, transfer: StockTransfer) -> StockTransfer: ...

    def find_by_id(self, transfer_id: str) -> Optional[StockTransfer]: ...

    def find_by_number(self, transfer_number: str) -> Optional[StockTransfer]: ...

    def list_all(self) -> List[StockTransfer]: ...

    def delete(self, transfer_id: str) -> None: ...
