export {
  SalesOverviewPage,
  SalesOrdersListPage,
  SalesOrderDetailPage,
  DeliveryNotesListPage,
  DeliveryNoteDetailPage,
  SalesInvoicesListPage,
  SalesInvoiceDetailPage,
  EstimatesListPage,
  EstimateDetailPage,
  QuotationsListPage,
  QuotationDetailPage,
  SalesReturnsListPage,
  SalesReturnDetailPage,
  SalesReportsPage,
  SalesScheduledReportsPage,
} from './pages';
