#!/usr/bin/env python3
"""Generate docs/parity-checklist.md from Streamlit url_path routes in app.py."""

from __future__ import annotations

import re
import sys
from datetime import datetime, timezone
from pathlib import Path

_URL_PATH_RE = re.compile(r'url_path="([^"]+)"')


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _parse_url_paths(app_py: Path) -> list[str]:
    text = app_py.read_text(encoding="utf-8")
    seen: set[str] = set()
    ordered: list[str] = []
    for match in _URL_PATH_RE.finditer(text):
        path = match.group(1).strip()
        if path and path not in seen:
            seen.add(path)
            ordered.append(path)
    return sorted(ordered)


def _permission_for_page(url_path: str) -> str:
    root = str(_repo_root())
    if root not in sys.path:
        sys.path.insert(0, root)
    try:
        from vaybooks.bms.domain.entitlements.catalog import permission_for_page

        return permission_for_page(url_path) or ""
    except ImportError:
        return ""


def _render_checklist(paths: list[str]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# VayBooks Route Parity Checklist",
        "",
        f"_Generated by `packages/tools/generate_parity_checklist.py` on {now}_",
        "",
        "Track migration parity for each Streamlit `url_path` route.",
        "",
        "| # | url_path | permission | migrated | notes |",
        "|---:|---|---|---|---|",
    ]
    for idx, path in enumerate(paths, start=1):
        perm = _permission_for_page(path)
        lines.append(f"| {idx} | `{path}` | `{perm}` | ☐ | |")
    lines.extend(["", f"**Total routes:** {len(paths)}", ""])
    return "\n".join(lines)


def main() -> int:
    root = _repo_root()
    app_py = root / "app.py"
    out_path = root / "docs" / "parity-checklist.md"

    if not app_py.is_file():
        print(f"ERROR: app.py not found at {app_py}", file=sys.stderr)
        return 1

    paths = _parse_url_paths(app_py)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(_render_checklist(paths), encoding="utf-8")
    print(f"Wrote {len(paths)} routes to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
